// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launchctl} from '../models';
import {main} from '../models';
import {plistutil} from '../models';
import {backup} from '../models';

export function CheckPermissions():Promise<Record<string, boolean>>;

export function CreateService(arg1:launchctl.ServiceConfig):Promise<void>;

export function CreateSystemService(arg1:launchctl.ServiceConfig):Promise<void>;

export function DeleteService(arg1:string):Promise<void>;

export function DeleteSystemService(arg1:string):Promise<void>;

export function DisableAdminMode():Promise<void>;

export function EnableAdminMode():Promise<void>;

export function GetAdminModeStatus():Promise<main.AdminModeStatus>;

export function GetBackupContent(arg1:string,arg2:string):Promise<plistutil.Content>;

export function GetCurrentPlist(arg1:string):Promise<plistutil.Content>;

export function GetCurrentSystemPlist(arg1:string):Promise<plistutil.Content>;

export function GetLogs(arg1:string,arg2:string):Promise<string>;

export function GetPlist(arg1:string):Promise<string>;

export function GetService(arg1:string):Promise<launchctl.Service>;

export function GetSystemLogs(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSystemPlist(arg1:string,arg2:string):Promise<string>;

export function GetSystemService(arg1:string,arg2:string):Promise<launchctl.Service>;

export function GetVersion():Promise<string>;

export function KickstartService(arg1:string):Promise<void>;

export function ListAllBackups():Promise<Array<backup.Backup>>;

export function ListAppleSystemServices():Promise<Array<launchctl.Service>>;

export function ListBackups(arg1:string):Promise<Array<backup.Backup>>;

export function ListServices():Promise<Array<launchctl.Service>>;

export function ListSystemServices():Promise<Array<launchctl.Service>>;

export function RestartService(arg1:string):Promise<void>;

export function RestartSystemService(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StartSystemService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function StopSystemService(arg1:string):Promise<void>;

export function UpdateService(arg1:string,arg2:launchctl.ServiceConfig):Promise<void>;

export function UpdateSystemService(arg1:string,arg2:launchctl.ServiceConfig):Promise<void>;
