// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateService(arg1) {
  return window['go']['main']['App']['CreateService'](arg1);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function GetBackupContent(arg1, arg2) {
  return window['go']['main']['App']['GetBackupContent'](arg1, arg2);
}

export function GetLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2);
}

export function GetPlist(arg1) {
  return window['go']['main']['App']['GetPlist'](arg1);
}

export function GetService(arg1) {
  return window['go']['main']['App']['GetService'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function UpdateService(arg1, arg2) {
  return window['go']['main']['App']['UpdateService'](arg1, arg2);
}
