// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPermissions() {
  return window['go']['main']['App']['CheckPermissions']();
}

export function CreateService(arg1) {
  return window['go']['main']['App']['CreateService'](arg1);
}

export function CreateSystemService(arg1) {
  return window['go']['main']['App']['CreateSystemService'](arg1);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function DeleteSystemService(arg1) {
  return window['go']['main']['App']['DeleteSystemService'](arg1);
}

export function DisableAdminMode() {
  return window['go']['main']['App']['DisableAdminMode']();
}

export function EnableAdminMode() {
  return window['go']['main']['App']['EnableAdminMode']();
}

export function GetAdminModeStatus() {
  return window['go']['main']['App']['GetAdminModeStatus']();
}

export function GetBackupContent(arg1, arg2) {
  return window['go']['main']['App']['GetBackupContent'](arg1, arg2);
}

export function GetCurrentPlist(arg1) {
  return window['go']['main']['App']['GetCurrentPlist'](arg1);
}

export function GetCurrentSystemPlist(arg1) {
  return window['go']['main']['App']['GetCurrentSystemPlist'](arg1);
}

export function GetLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2);
}

export function GetPlist(arg1) {
  return window['go']['main']['App']['GetPlist'](arg1);
}

export function GetService(arg1) {
  return window['go']['main']['App']['GetService'](arg1);
}

export function GetSystemLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSystemLogs'](arg1, arg2, arg3);
}

export function GetSystemPlist(arg1, arg2) {
  return window['go']['main']['App']['GetSystemPlist'](arg1, arg2);
}

export function GetSystemService(arg1, arg2) {
  return window['go']['main']['App']['GetSystemService'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function KickstartService(arg1) {
  return window['go']['main']['App']['KickstartService'](arg1);
}

export function ListAllBackups() {
  return window['go']['main']['App']['ListAllBackups']();
}

export function ListAppleSystemServices() {
  return window['go']['main']['App']['ListAppleSystemServices']();
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function ListSystemServices() {
  return window['go']['main']['App']['ListSystemServices']();
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function RestartSystemService(arg1) {
  return window['go']['main']['App']['RestartSystemService'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StartSystemService(arg1) {
  return window['go']['main']['App']['StartSystemService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function StopSystemService(arg1) {
  return window['go']['main']['App']['StopSystemService'](arg1);
}

export function UpdateService(arg1, arg2) {
  return window['go']['main']['App']['UpdateService'](arg1, arg2);
}

export function UpdateSystemService(arg1, arg2) {
  return window['go']['main']['App']['UpdateSystemService'](arg1, arg2);
}
