// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launchctl} from '../models';
import {backup} from '../models';

export function CreateService(arg1:launchctl.ServiceConfig):Promise<void>;

export function DeleteService(arg1:string):Promise<void>;

export function GetBackupContent(arg1:string,arg2:string):Promise<string>;

export function GetLogs(arg1:string,arg2:string):Promise<string>;

export function GetPlist(arg1:string):Promise<string>;

export function GetService(arg1:string):Promise<launchctl.Service>;

export function ListBackups(arg1:string):Promise<Array<backup.Backup>>;

export function ListServices():Promise<Array<launchctl.Service>>;

export function RestartService(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function UpdateService(arg1:string,arg2:launchctl.ServiceConfig):Promise<void>;
